on:
  push:

jobs:
  reuse-action:
    runs-on: ubuntu-latest
    steps:
      - name: Reuse custom action
        id: reuse-action-step
        uses: Danish-Spots/private-action@main
        with:
          who-to-greet: 'DS'
      - name: Get output time
        run: echo "The time was  ${{ steps.reuse-action-step.outputs.time }}."

      - name: Something to change for commits
        run: echo "something to change 1"
