on:
  push:

jobs:
  reuse-action:
    runs-on: ubuntu-latest
    steps:
      - name: Reuse custom action
        id: reuse-action-step
        uses: Danish-Spots/private-action@ddc8ef31fc80c0615de6092ff633f8bfb05312b6
        with:
          who-to-greet: 'DS'
      - name: Get output time
        run: echo "The time was  $ {{ steps.reuse-action-step.outputs.time }}."
